services:
  - type: web
    name: tplab2-app
    runtime: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      gunicorn tplab2.wsgi:application --preload
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: tplab2.settings
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: tplab2-db
          property: connectionString

databases:
  - name: postgres
    plan: free
