# Exported from Render on 2025-11-17T14:13:40Z
version: "1"
projects:
- name: lab2-rednyakov
  environments:
  - name: Production
    services:
    - type: web
      name: PTLab2
      runtime: python
      repo: https://github.com/Atr1a/PTLab2
      plan: free
      envVars:
      - key: DATABASE_URL
        sync: false
      region: oregon
      buildCommand: pip install -r requirements.txt && python manage.py makemigrations
        && python manage.py migrate && python manage.py loaddata products.yaml
      startCommand: 'gunicorn app:app '
      autoDeployTrigger: commit
    databases:
    - name: postgres
      databaseName: postgres_3r0q
      user: postgres_3r0q_user
      plan: free
      region: oregon
      ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere
      postgresMajorVersion: "18"
